### ISSUE TITLE
Suggestion for MagSafe indicator light

### ISSUE THREAD

**Issue by SuperLeiyan** [mhaeuser/Battery-Toolkit#45]
Love the new feature, but I personally find the blinking distracting, perhaps keep it simple and more inline with Apple's original design:

Charging = Glowing Amber
On Hold / Disabled = OFF
Fully Charged = Glowing Green

Or 'Glowing Red' for 'On Hold', though I don't know if the hardware supports this.

Charging = Glowing Amber
On Hold = Glowing Red
Disabled = OFF
Fully Charged = Glowing Green

**Comment by mhaeuser** [comment]
The color, to my knowledge, is not freely configurable. I don't like the ambiguity of "on hold"/"disabled", because that's an important distinction. The distinction of "on hold" and "fully charged" is not that important, I'd rather sacrifice that, but that still feels awkward. I don't think this can be resolved cleanly, sorry.
