### ISSUE TITLE
Battery settings are stuck after uninstalling the app

### ISSUE THREAD

**Issue by boramerts** [mhaeuser/Battery-Toolkit#54]
I've installed the app yesterday and I've enabled settings as below. Today, I've uninstalled the app but now my M4 MacBook Pro is not charging above 76%

<img width="495" alt="image" src="https://github.com/user-attachments/assets/ef74ec08-1c86-4d30-acf2-0e103018a755">

I've tried multiple plugs, my charge adapter and magsafe cable are original but it always "Battery is not charging"

<img width="290" alt="image" src="https://github.com/user-attachments/assets/4b6669ca-6c4c-47dd-a384-d2336d6fd0ad">

**Comment by mhaeuser** [comment]
I’m surprised I keep getting such reports, because it is literally impossible. Past Ventura, all executables remain within the app bundle and Apple Silicon SMC is stateless, so when you delete the app bundle and reboot, there is no technical possibility Battery Toolkit interferes with anything. Use Activity Monitor to locate the app bundle location.

**Comment by N0ne1eft** [comment]
Check whether you have emptied Trash. Just tried to replicate this issue myself and I discovered that the daemon will still be running from Trash, emptying the Trash followed by a restart allows the charging to revert back to system control.
<img width="1068" alt="Pasted Graphic" src="https://github.com/user-attachments/assets/e1413edb-1eb4-4085-b38a-9c8897a99d83" />
